services:
  worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/hatchet/epengine:${ENERGYPLUS_VERSION:-22.2.0}
    build:
      context: .
      dockerfile: epengine/worker/Dockerfile
      args:
        - ENERGYPLUS_VERSION=${ENERGYPLUS_VERSION:-22.2.0}
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./artifacts:/artifacts

  api:
    build:
      context: .
      dockerfile: epengine/api/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
