services:
  aws:
    image: motoserver/moto:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aws:${MOTO_PORT}/moto-api/data.json"]
      interval: 5s
      retries: 3
      timeout: 10s
      start_period: 15s
    ports:
      - "${MOTO_PORT}:${MOTO_PORT}"
    environment:
      - MOTO_PORT=${MOTO_PORT}
  initialize:
    build:
      context: .
      dockerfile: epengine/initialize/Dockerfile
    depends_on:
      aws:
        condition: service_healthy
    env_file:
      - .env.dev
  api:
    command: ["--reload"]
    volumes:
      - ./epengine:/code/epengine
    restart: always
    depends_on:
      initialize:
        condition: service_completed_successfully
    env_file:
      - .env.dev
  worker:
    depends_on:
      initialize:
        condition: service_completed_successfully
    env_file:
      - .env.dev
    volumes:
      - ./epengine:/code/epengine
