services:
  worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/hatchet/epengine:ep${EP_VERSION:-22.2.0}-py${PYTHON_VERSION:-3.12}
    build:
      context: .
      dockerfile: epengine/worker/Dockerfile
      args:
        - EP_VERSION=${EP_VERSION:-22.2.0}
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
        - POETRY_VERSION=${POETRY_VERSION:-2.1.2}
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./artifacts:/artifacts
      - ./epengine:/code/epengine

  api:
    build:
      context: .
      dockerfile: epengine/api/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
